Repository 2024-likelion-sswu/Funit_FE, pull requests merged in 2025-01, with the labels that each got.

#3 [Feature] #1 - 스플래시 화면 구현
  src/assets/img/main/background.svg
  src/assets/img/main/splash.png
  src/assets/sass/section/_main.scss
  src/assets/sass/setting/_reset.scss
  src/assets/sass/setting/_var.scss
  src/pages/mainPage/MainPage.jsx
Labels: 🎨 Design, ✨ Feature, 👩나경

#12 [Feature] #4 - 테스트 작성 페이지 UI 구현
  src/App.js
  src/assets/img/test/copy.svg
  src/assets/img/test/next.png
  src/assets/sass/section/_onboarding.scss
  src/assets/sass/section/_questionCreate.scss
  src/assets/sass/section/_testCreate.scss
  src/assets/sass/setting/_common.scss
  src/assets/sass/style.scss
  src/components/QuestionCreate.jsx
  src/pages/testCreatePage/OnboardingPage.jsx
  src/pages/testCreatePage/TestCreatePage.jsx
Labels: 🎨 Design, ✨ Feature, 👩나경

#13 [Feature] #4 - 질문 10개 미만 선택시 뷰 구현
  src/App.js
  src/assets/sass/section/_onboarding.scss
  src/assets/sass/setting/_common.scss
  src/pages/testCreatePage/OnboardingPage2.jsx
Labels: 🎨 Design, ✨ Feature, 👩나경

#15 [Feature] #4 - 나만의 질문 만들기 페이지 UI 구현
  src/App.js
  src/assets/sass/section/_questionCreate.scss
  src/assets/sass/section/_testCustom.scss
  src/assets/sass/style.scss
  src/components/QuestionCreate.jsx
  src/components/QuestionCustom.jsx
  src/pages/testCreatePage/OnboardingPage2.jsx
  src/pages/testCreatePage/TestCustomPage.jsx
Labels: 🎨 Design, ✨ Feature, 👩나경

#17 [Feature] #16 - URL 공유 및 편지 작성 페이지 UI 구현
  src/App.js
  src/assets/img/character/pink.png
  src/assets/img/character/skyblue.png
  src/assets/img/character/yelloweye.png
  src/assets/img/letter/checkBlue.svg
  src/assets/img/letter/checkPink.svg
  src/assets/img/letter/checkYellow.svg
  src/assets/sass/section/_letterCreate.scss
  src/assets/sass/section/_urlShare.scss
  src/assets/sass/style.scss
  src/pages/letterPage/LetterCreatePage.jsx
  src/pages/testCreatePage/UrlSharePage.jsx
Labels: 🎨 Design, ✨ Feature, 👩나경

#19 [Feature] #18 - 편지 내용 페이지 UI 구현
  src/App.js
  src/assets/img/letter/letterOpen.png
  src/assets/sass/section/_letterRead.scss
  src/assets/sass/style.scss
  src/pages/letterPage/LetterReadPage.jsx
Labels: 🎨 Design, ✨ Feature, 👩나경

#27 [Design] #26 - 편지 내용 페이지 UI 수정
  src/App.js
  src/assets/sass/section/_letterRead.scss
  src/pages/letterPage/LetterReadPage.jsx
  src/pages/letterPage/LetterTreePage.jsx
Labels: 🎨 Design, 👩나경

#30 [Feature] #28 - 닉네임 페이지 API 연결
  package.json
  src/assets/sass/section/_nickname.scss
  src/pages/mainPage/MainPage.jsx
  src/pages/testCreatePage/NicknamePage.jsx
  src/pages/testCreatePage/OnboardingPage.jsx
Labels: 🔗 API, ✨ Feature, 👩나경

#33 [Fix] #31 - 로그인 403 에러 수정
  .env
  package-lock.json
  package.json
  src/apis/axiosInstance.js
  src/assets/sass/section/_questionCreate.scss
  src/components/QuestionCreate.jsx
  src/pages/testCreatePage/NicknamePage.jsx
  src/pages/testCreatePage/OnboardingPage.jsx
  src/pages/testCreatePage/TestCreatePage.jsx
Labels: 🔗 API, 🛠️ Fix, 👩나경

#35 [Feature] #29 - 랭킹 api 연동
  package-lock.json
  src/pages/testCreatePage/NicknamePage.jsx
  src/pages/testScorePage/RankingPage.jsx
Labels: 🔗 API, 👩예은

#34 [Feature] #31 - 질문 가져오기 에러 수정 중
  .env
  src/apis/axiosInstance.js
  src/components/QuestionCreate.jsx
  src/components/QuestionCustom.jsx
  src/pages/testCreatePage/NicknamePage.jsx
  src/pages/testCreatePage/OnboardingPage.jsx
  src/pages/testCreatePage/OnboardingPage2.jsx
  src/pages/testCreatePage/TestCreatePage.jsx
  src/pages/testCreatePage/TestCustomPage.jsx
  src/pages/testCreatePage/UrlSharePage.jsx
Labels: 🔗 API, 👩나경

#36 [Feature] #31 - 랜덤 질문 생성 API 연결
  src/assets/sass/section/_questionCreate.scss
  src/components/QuestionCustom.jsx
  src/pages/testCreatePage/NicknamePage.jsx
  src/pages/testCreatePage/OnboardingPage2.jsx
  src/pages/testCreatePage/TestCustomPage.jsx
  src/pages/testCreatePage/UrlSharePage.jsx
Labels: 🔗 API, ✨ Feature, 👩나경

#37 [Feature] #31 - 질문 커스텀 API 연결
  src/pages/testCreatePage/TestCreatePage.jsx
  src/pages/testCreatePage/TestCustomPage.jsx
Labels: 🔗 API, ✨ Feature, 👩나경

#39 [Feature]#32 - 테스트 페이지 api 연동
  src/apis/axiosInstance.js
  src/components/QuestionCreate.jsx
  src/pages/testCreatePage/NicknamePage.jsx
  src/pages/testPage/TestPage.jsx
  src/pages/testScorePage/RankingPage.jsx
  src/pages/testScorePage/Score1Page.jsx
  src/pages/testScorePage/Score2Page.jsx
  src/pages/testScorePage/Score3Page.jsx
Labels: 🔗 API, 👩예은
